// Generated by CoffeeScript 1.6.3
(function() {
  var codeViewer, currentSlide, getTop, goNextSlide, goPrevSlide, mode, showCode, showSlide, slides, slideshow, top;

  top = null;

  mode = 'edit';

  currentSlide = 0;

  slides = $('#slides');

  slideshow = $('#slideshow');

  codeViewer = $('#code-viewer');

  $(window).on('unload', function() {
    return viol.send('final_y_position', top || $('body').scrollTop());
  });

  $('body').on('click', '.slide pre', function() {
    var code;
    code = $(this).text();
    return showCode(code);
  });

  $('#code-viewer').on('click', function() {
    codeViewer.hide();
    if (mode === 'edit') {
      slides.show();
      $('body').scrollTop(top);
      return top = null;
    }
  });

  $('body').on('click', 'button.start', function() {
    mode = 'slideshow';
    slides.hide();
    slideshow.show();
    showSlide(currentSlide);
    return $(window).on('keyup', function(evt) {
      var code;
      code = evt.keyCode;
      if (code === 40) {
        return goNextSlide();
      } else if (code === 38) {
        return goPrevSlide();
      } else if (code === 27) {
        mode = 'edit';
        $(window).off('keyup');
        slideshow.hide();
        return slides.show();
      }
    });
  });

  $('body').on('click', 'div[demo] a', function(evt) {
    evt.preventDefault();
    return viol.send('demo_path', $(this).attr('href'));
  });

  $('body').on('click', 'div[demo] button', function() {
    var div;
    div = $(this).parents('div[demo]');
    viol.send('run_demo', div.attr('demo'));
    return window.open('http://localhost:8000', '_blank');
  });

  viol.on('render_slides', function(html) {
    var first, index;
    slides.empty();
    first = $('#first-slide').clone().attr('id', '').show();
    slides.append(first);
    slides.append(html);
    first.find('.slide-count').text(slides.find('div.slide').length - 1);
    first.find('.notes-count').text(slides.find('div.slide.notes').length - 1);
    index = 0;
    return slides.find('div.slide').each(function() {
      var slide;
      slide = $(this);
      if (!slide.hasClass('notes')) {
        slide.attr('data-index', index);
        return index++;
      }
    });
  });

  viol.on('demo_code', function(code) {
    return showCode(code);
  });

  showCode = function(code) {
    var pre;
    codeViewer.show();
    pre = $('<pre></pre>');
    pre.text(code);
    codeViewer.empty().append(pre);
    if (mode === 'edit') {
      top = getTop();
      return slides.hide();
    }
  };

  getTop = function() {
    return $('body').scrollTop();
  };

  goNextSlide = function() {
    return showSlide(currentSlide + 1);
  };

  goPrevSlide = function() {
    return showSlide(currentSlide - 1);
  };

  showSlide = function(slideIndex) {
    var slide;
    slide = slides.find('div.slide[data-index=' + slideIndex + ']');
    if (slide.length !== 0) {
      currentSlide = slideIndex;
      return slideshow.empty().append(slide.clone());
    }
  };

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
