// Generated by CoffeeScript 1.6.3
(function() {
  var sendEditMessage;

  sendEditMessage = function() {
    return viol.send('edit', {
      input: $('textarea[name=input]').val(),
      regex: $('textarea[name=regex]').val()
    });
  };

  $(document).ready(function() {
    $('textarea').on('change', function() {
      return sendEditMessage();
    });
    $('textarea').on('keyup', function() {
      return sendEditMessage();
    });
    return $('textarea[name=regex]').on('keydown', function(evt) {
      if (evt.keyCode === 9) {
        evt.preventDefault();
        return $('textarea[name=input]').focus();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
